import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/navbar";
import Model from "@/components/Model/model";
import About from "@/components/About/about";
import Achievements from "@/components/Achievements/achievements";
import Contact from "@/components/Contact/contact";
import StarsCanvas from "@/components/Canvas/Stars";

export default function Home() {
  return (
    <>
      <Head>
        <title>MaRS IITR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <main>
        <div className="relative z-0 bg-primary">
          <div className="bg-hero-pattern bg-cover bg-no-repeat bg-center">
            <Navbar />
            <Model />
          </div>
          <About />
          <Achievements />
          <div className="relative z-0">
            <Contact />
            <StarsCanvas />
          </div>
          {/* <hr className="mt-2 bg-gradient-to-r from-emerald-900 to-fuchsia-900" /> */}
          <div>
            <div className="my-6 flex justify-center gap-5">
              <img src="https://cdn-icons-png.flaticon.com/128/3955/3955024.png" alt="insta" width={30} className="cursor-pointer" />
              <img src="https://cdn-icons-png.flaticon.com/128/5969/5969020.png" alt="twitter" width={30} className="cursor-pointer" />
              <img src="https://cdn-icons-png.flaticon.com/128/5968/5968764.png" alt="facebook" width={30} className="cursor-pointer" />
              <img src="https://cdn-icons-png.flaticon.com/128/145/145807.png" alt="linkedin" width={30} className="cursor-pointer" />
            </div>
            <div className="text-center pb-6">
              <p>Made with ❤️ by MaRS, IITR</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
